---

- name: "devenv.tasks._debian: Install packages depend on pyenv"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - zlib1g-dev
    - libssl-dev
    - libbz2-dev
    - libffi-dev
    - libreadline-dev
    - libsqlite3-dev

- name: "devenv.tasks._debian: Include pyenv task"
  include_tasks: _pyenv.yml

- name: "devenv.tasks._debian: Add repository"
  apt_repository:
    repo: ppa:neovim-ppa/stable

- name: "devenv.tasks._debian: Install repository from neovim-ppa/stable"
  apt:
    name: "neovim"
    state: latest
    update_cache: yes

- name: "devenv.tasks._debian: Include Neovim task"
  include_tasks: _neovim.yml

